before_install:
  - export NIX_CONF_DIR=~
  - echo "binary-caches = https://cache.nixos.org https://vaibhavsagar.cachix.org" >> $NIX_CONF_DIR/nix.conf
  - echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= vaibhavsagar.cachix.org-1:PxFckJ8oAzgF4sdFJ855Fw38yCVbXmzJ98Cc6dGzcE0=" >> $NIX_CONF_DIR/nix.conf
language: nix
nix: 2.2.2
script: nix-build -A travis
notifications:
  email:
    on_failure: always
after_success: bash .ci/update_pages.sh
before_deploy:
- nix-build -A pdf
deploy:
  provider: releases
  file: result/Vaibhav_Sagar_resume.pdf
  on:
    repo: vaibhavsagar/resume
    all_branches: true
    tags: true
  api_key:
    secure: gtBPUeDXL9S6h4aWyXCEhWxbtkATx2lIBmkVTcWDHMvgwQHmfo42OPq7rQWjO6g/iOlv71Q1VQMQc84ERcZjtBRSE0pb1s1Baqs2Hk7ec/JeWsEXDZmBIs/Z3V6pHb14zCs5GNYyerXDpQ97P4RG9Vjdy+rc3I1+kkuCMF7zB3k=
env:
  global:
    secure: Bzof/7yN7HgV2eJk7FNliNx/cagIU4I113SwNJhChFyYOSy816oPrwQaCMyZuwvbcEIfLMY0K0qxtQK1MoPq7zTYiCTW3UPB2+mzTfTHPMTm5nWjZv0BmdqVoG8IJwxfo5cIV8hfKiu2ezNKcDuqgwb80mYwpTwlQPsY9gOm1Tc=
