language: nix

cache:
  directories:
  - /nix/store
install:
- nix-env -i pandoc
script: make travis
notifications:
  email:
    on_failure: always
after_success:
- bash .ci/update_pages.sh
- nix-collect-garbage
before_deploy:
- nix-env -i texlive-combined-full-2016
- make pdf
deploy:
  provider: releases
  file: Vaibhav_Sagar_resume.pdf
  on:
    repo: vaibhavsagar/resume
    all_branches: true
    tags: true
  api_key:
    secure: gtBPUeDXL9S6h4aWyXCEhWxbtkATx2lIBmkVTcWDHMvgwQHmfo42OPq7rQWjO6g/iOlv71Q1VQMQc84ERcZjtBRSE0pb1s1Baqs2Hk7ec/JeWsEXDZmBIs/Z3V6pHb14zCs5GNYyerXDpQ97P4RG9Vjdy+rc3I1+kkuCMF7zB3k=
env:
  global:
    secure: Bzof/7yN7HgV2eJk7FNliNx/cagIU4I113SwNJhChFyYOSy816oPrwQaCMyZuwvbcEIfLMY0K0qxtQK1MoPq7zTYiCTW3UPB2+mzTfTHPMTm5nWjZv0BmdqVoG8IJwxfo5cIV8hfKiu2ezNKcDuqgwb80mYwpTwlQPsY9gOm1Tc=
